// <auto-generated />
using System;
using DotnetCards.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotnetCards.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211222163155_migration")]
    partial class migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DotnetCards.Core.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentPostId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentPostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2021, 12, 22, 19, 31, 54, 756, DateTimeKind.Local).AddTicks(7170),
                            Title = "Post1"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2021, 12, 22, 19, 31, 54, 758, DateTimeKind.Local).AddTicks(2440),
                            Title = "Post2"
                        });
                });

            modelBuilder.Entity("DotnetCards.Core.Models.PostDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("PostText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("PostDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PostId = 1,
                            PostText = "Post Detail 1"
                        },
                        new
                        {
                            Id = 2,
                            PostId = 2,
                            PostText = "Post Detail 2"
                        });
                });

            modelBuilder.Entity("DotnetCards.Core.Models.Post", b =>
                {
                    b.HasOne("DotnetCards.Core.Models.Post", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentPostId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DotnetCards.Core.Models.PostDetail", b =>
                {
                    b.HasOne("DotnetCards.Core.Models.Post", "Post")
                        .WithMany("PostDetails")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("DotnetCards.Core.Models.Post", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("PostDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
